language: python
env:
  - DJANGO_VERSION=">=1.11,<1.12.0"
  - DJANGO_VERSION=">=2.2,<2.3"
  - DJANGO_VERSION=">=3.0,<3.1"
python:
    - '2.7'
    - '3.6'
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO_VERSION=">=2.2,<2.3"
  - python: '2.7'
    env: DJANGO_VERSION=">=3.0,<3.1"
install:
  - pip install -q Django$DJANGO_VERSION
script: python run_tests.py
